.TH HUNSPELL 1 "2026-01-01"
.SH NAME
hunspell \- spell checker and morphologcal analyzer
.SH SYNOPSIS
\fBhunspell\fR [\fIoptions\fR] [\fIfilee\fR]
.B boldd macro argument
.PP
This is a manuall page with mistaeks.
Escapes \fBbolld\fP and \fIitalc\fR and \(em dash.
.\" a coment line wih errors
.I
Normal textt after an argless macro.
